### ISSUE TITLE
Mime types not recognized

### ISSUE THREAD

**Issue by AdrianVollmer** [AdrianVollmer/Zundler#2]
@humitos reported  an issue [here](https://github.com/sphinx-doc/sphinx/issues/10688#issuecomment-1282146524)  with the document in question [here](https://test-builds.readthedocs.io/en/sphinx-docs-zundler/).

The document tries to open lots of `blob:` URLs in a new tab. That is the default behavior for files with a mime type other than `text/html`. In this case, the mime type is not detected properly. Zundler uses `python-magic` for that, which is a wrapper around a C library. I am guessing that this C library is missing on the system that built the document. (There should have been errors on the command line while building it.)

I'm thinking about a good workaround for that. Guessing mime types can be unreliable, which is probably why the Python library resorts to a mature C library. We could fall back to the built-in [mimetypes](https://docs.python.org/3/library/mimetypes.html), which should work sufficiently well for well-behaved documents (which most Sphinx docs are).

**Comment by humitos** [comment]
Cool! Thanks for the detailed explanation. Knowing that `python-magic` relies in a C library was the key. I just went to the official docs of python-magic and found that it requires on `libmagic1` on Ubuntu. So, I installed that in the build pipeline of Read the Docs and now it works!

The original build output showed this error:

```
embedding HTML assets... Error while guessing mime type: b'# Sphinx b'...
failed to find libmagic.  Check your installation
```

Now, after installing the C library that message disappeared 👍🏼 

Check it out the working version at: https://test-builds.readthedocs.io/en/sphinx-docs-zundler/. There is the YAML config file used that shows the packages installed and the `requirements.txt` as well.

I think we can close this issue now 💪🏼
