### ISSUE TITLE
Example for jupyter-book

### ISSUE THREAD

**Issue by davibicudo** [AdrianVollmer/Zundler#3]
Hi

Could you add an example or clarify how to run with Jupiter-book? I tried as you suggested in the README to add 

['html', 'zundler', 1]

to the _config.yml at

sphinx:
  config:
    nb_mime_priority_overrides: [

but it has no effect. Did I do it wrong or something?

Thanks in advance.

**Comment by AdrianVollmer** [comment]
You're right, either something changed meanwhile or I forget to put `--builder custom` in there. For whatever reason you need to tell `jupyter-book` twice that you want a custom builder. I'll update the readme.

**Comment by davibicudo** [comment]
Works perfectly, thanks a lot!
