### ISSUE TITLE
AttributeError("'str' object has no attribute 'joinpath'")

### ISSUE THREAD

**Issue by virtualbs** [AdrianVollmer/Zundler#4]
Hi, using the latest version of Sphinx (7.2.6) and the Furo theme (2023.9.10), I'm getting this error:

```
(...)
done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [zundler]: targets for 5 source files that are out of date
updating environment: [new config] 5 added, 0 changed, 0 removed
reading sources... [100%] file1
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
writing output... [ 20%] file2
Theme error:
An error happened in rendering the page file2.
Reason: AttributeError("'str' object has no attribute 'joinpath'")
```

I have a different conda env running Sphinx 6.1.3 and furo 2022.12.7 that works flawlessly.

If you need further info, please let me know. Thank you.

**Comment by AdrianVollmer** [comment]
Are you sure this is related to Zundler? Zunder never uses `joinpath`, so I'm confused.

Can you please post the full command you are executing, and also add the `-T` argument so we can see the full stack trace.

**Comment by virtualbs** [comment]
Thanks for the `-T` suggestion, it was easy to find out the problem afterwards. I was running the `make.bat` of a sphynx project, where `make html` worked, but `make zundler` did not.

I only have this error in Sphinx >= 7.2.0, and the culprit is an unhandled `AttributeError` exception in function `_file_checksum` of `_assets.py` (located at `...\sphinx\builders\html\`), inside the `try` block starting at line 139.

The fix was changing the `FileNotFoundError` exception at line 142 (`except FileNotFoundError`) to a more general `Exception`, which is sufficient to also handle `AttributeError`. A more conservative approach would be to change it to `except (FileNotFoundError, AttributeError)`.

Still, the raise `AttributeError` only happens on `make zundler`, and not in `make html`; I did not further explore the causes.

Anyway, thank you for your help!

**Comment by AdrianVollmer** [comment]
Yeah, Zundler is passing `outdir` as a string to Sphinx and in Sphinx 7.2 it must be a `Path` object. Thanks for reporting, I'll fix this!
