### ISSUE TITLE
Code copying broken with the latest version

### ISSUE THREAD

**Issue by JaGeo** [AdrianVollmer/Zundler#6]
Unfortunately, now the copy button for code is broken with the latest version. It might be related to the changes in 
https://github.com/AdrianVollmer/Zundler/issues/5

![image](https://github.com/AdrianVollmer/Zundler/assets/22094846/49670baa-5305-4775-9a46-895842d622d7)

I have adapted the minimal example here.

[Minmal_Example.zip](https://github.com/AdrianVollmer/Zundler/files/14756415/Minmal_Example.zip)

**Comment by AdrianVollmer** [comment]
Yes I should really start defining some integration tests... thanks for reporting, will take a look!

**Comment by AdrianVollmer** [comment]
Please try again

**Comment by JaGeo** [comment]
Thank you! I will!

**Comment by JaGeo** [comment]
It works. I tested a few other options as well and it all seems to work! Thank you so much!

**Comment by AdrianVollmer** [comment]
No problem, thanks again for reporting the issue
