### ISSUE TITLE
Problem with search functionality, when using Sphinx RTD theme.

### ISSUE THREAD

**Issue by NogayKuepelioglu-Synthara** [AdrianVollmer/Zundler#8]
Hello @AdrianVollmer 

Not sure if it was reported before, or you are aware of it. I have a documentation in which I am using Sphinx with the RTD theme, and when I was testing the documentation file I realized that the search functionality does not work. I have noticed that the same issue exists on your example of the ReadTheDocs as well. 

Basically the search gets stuck, because `searchindex.js` cannot be found.

For reference:
- I am testing it on a Ubuntu 22.04 system with Firefox (version: 128.0.2)
- I have also tested it with Chromium (version: 126.0.6478.182) the same problem exists.

All your other examples seem to work.

![bug_rtd_zundler](https://github.com/user-attachments/assets/95705fdb-bcf4-43ff-8733-6542713ca21a)

**Comment by AdrianVollmer** [comment]
Yes, this is because RTD is still using jQuery and for some reason it doesn't play nicely. Thanks for pointing it out, I'll have to investigate.

**Comment by AdrianVollmer** [comment]
Nevermind, it wasn't jQuery's fault, but mine
